import fullbody from './fullbody.png';
import border from './outerborder.png';
import title from './title.png';
import ribbon from './ribbon for name.png';
import stamp from './stamp.png';
import footer from './footer.png';
import accountsign from './Dvg_Reddy[1].png';
import vamsisign from './vamsisign.png';
import sumithsign from './sumitsign.png';
import devsign from './devsign.png';
import landscapebg from './fullbody-landscape.png';
import portraitbg from './fullbody-portrait.png';
export { fullbody, border , title, ribbon, stamp, footer, accountsign, vamsisign, sumithsign,devsign, landscapebg, portraitbg }; 
